- name: 创建TLS临时目录
  file:
    path: "{{tmp_tls_dir}}"
    state: directory

- name: 创建 ca-config.json
  template:
    src: ca-config.json.j2
    dest: "{{tmp_tls_dir}}/ca-config.json"

- name: 创建 ca-config.json
  template:
    src: ca-csr.json.j2
    dest: "{{tmp_tls_dir}}/ca-csr.json"

- name: 生成ca证书
  shell: "openssl genrsa -out ca-key.pem 2048 && openssl req -new -x509 -days 36500 -key ca-key.pem -out ca.pem -subj '/C=CN/ST=BeiJing/L=BeiJing/O=k8s/OU=System/CN=kubernetes'"
  args:
    chdir: "{{tmp_tls_dir}}"