- name: 创建 log 目录
  become: true
  file:
    path: "{{data_base_dir}}/log"
    state: directory

- name: 复制kubernetes master执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.kubernetes_master}}"

- name: 生成 kubernetes master 相关服务
  become: true
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
  - kube-apiserver.service
  - kube-controller-manager.service
  - kube-scheduler.service