- name: 创建 etcd 数据目录
  become: true
  file:
    path: /var/lib/etcd
    state: directory

- name: 复制 etcd 执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.etcd}}"

- name: 生成 etcd 服务
  become: true
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: 启动 etcd 服务
  become: true
  systemd:
    enabled: yes
    daemon_reload: yes
    name: etcd
    state: started

- name: 设置 docker 网段参数
  become: true
  shell: "/usr/local/bin/etcdctl \
  --ca-file=/etc/kubernetes/ssl/ca.pem \
  --cert-file=/etc/flanneld/ssl/flanneld.pem \
  --key-file=/etc/flanneld/ssl/flanneld-key.pem \
  set /kubernetes/network/config '{ \"Network\" : \"{{cluster_cidr}}\" }'"