- name: 复制 flannel 执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.flannel}}"

- name: 生成 flannel 服务
  become: true
  template:
    src: flanneld.service.j2
    dest: /etc/systemd/system/flanneld.service