- name: 复制 kubernetes client 执行文件
  become: true
  copy:
    src: "{{tmp_bin_dir}}/{{item}}"
    dest: "{{bin_dir}}"
    mode: 0755
  with_items:
  - "{{bin_files.kubernetes_client}}"

- name: 设置 kubernetes client
  become: true
  shell: "{{item}}"
  with_items:
  - "{{bin_dir}}/kubectl config set-cluster kubernetes \
       --certificate-authority={{cert_ca_dir}}/ca.pem \
       --embed-certs=true \
       --server={{kube_apiserver}}"

  - "{{bin_dir}}/kubectl config set-credentials admin \
       --client-certificate={{cert_kubernetes_dir}}/admin.pem \
       --embed-certs=true \
       --client-key={{cert_kubernetes_dir}}/admin-key.pem"

  - "{{bin_dir}}/kubectl config set-context kubernetes \
       --cluster=kubernetes \
       --user=admin"

  - "{{bin_dir}}/kubectl config use-context kubernetes"