- name: 检测 kubernetes node 服务文件是否存在
  stat:
    path: "/etc/systemd/system/{{item}}.service"
  register: file
  with_items:
  - kubelet
  - kube-proxy

- name: 停止 kubernetes node 服务
  become: true
  systemd:
    state: stopped
    enabled: no
    name: "{{item.item}}" # item.item为服务文件名称，也就是上一个任务的item
  with_items:
  - "{{file.results}}"
  when: item.stat.exists == true

- name: 删除 kubernetes node 相关服务文件
  become: true
  file:
    path: "/etc/systemd/system/{{item}}.service"
    state: absent
  with_items:
  - kubelet
  - kube-proxy

- name: 获取 kubelet 挂载的目录
  become: true
  shell: "mount | grep '{{data_base_dir}}/kubelet'| awk '{print $3}'"
  args:
    warn: no
  register: mount_files

- name: unmount kubelet 挂载的目录
  become: true
  mount:
    path: "{{item}}"
    state: unmounted
  with_items:
  - "{{mount_files.stdout_lines}}"

- name: 删除 kubeconfig 文件
  become: true
  file:
    path: "{{kubernetes_conf_dir}}/{{item}}"
    state: absent
  with_items:
  - bootstrap.kubeconfig
  - kubelet.kubeconfig
  - kube-proxy.kubeconfig

- name: 删除 kubernetes node 执行文件
  become: true
  file:
    path: "{{bin_dir}}/{{item}}"
    state: absent
  with_items:
  - "{{bin_files.kubernetes_node}}"

- name: 删除 kubernetes node 数据目录
  become: true
  file:
    path: "{{item}}"
    state: absent
  with_items:
  - "{{data_base_dir}}/kubelet"
  - "{{data_base_dir}}/kube-proxy"