- name: 创建镜像临时目录
  file:
    path: "{{tmp_images_dir}}"
    state: directory

- name: 获取镜像文件
  copy:
    src: "{{playbook_dir}}/../images/{{item}}"
    dest: "{{tmp_images_dir}}"
  with_items:
  - "{{load_image_list}}"

- name: "导入 kubernetes 组件镜像"
  become: true
  shell: "{{bin_dir}}/docker load -i {{tmp_images_dir}}/{{item}}"
  with_items:
  - "{{load_image_list}}"