- name: "删除 helm"
  gather_facts: no
  hosts: client[0]
  roles:
  - del_helm
  tags:
  - del_helm

- name: "卸载 kubernetes node"
  gather_facts: no
  hosts: node
  roles:
  - del_kubernetes_node
  tags:
  - del_kubernetes_node

- name: "卸载 kubernetes client"
  gather_facts: no
  hosts: client
  roles:
  - del_kubernetes_client
  tags:
  - del_kubernetes_client

- name: "卸载 kubernetes master"
  gather_facts: no
  hosts: master
  roles:
  - del_kubernetes_master
  tags:
  - del_kubernetes_master

- name: "卸载 docker"
  gather_facts: no
  hosts: node
  roles:
  - del_docker
  tags:
  - del_docker

- name: "卸载 flannel"
  gather_facts: no
  hosts: node:master
  roles:
  - del_flannel
  tags:
  - del_flannel

- name: "卸载etcd"
  gather_facts: no
  hosts: etcd
  roles:
  - del_etcd
  tags:
  - del_etcd

- name: "卸载 kubernetes master load balance"
  gather_facts: no
  hosts: lb
  roles:
  - del_kubernetes_master_lb
  tags:
  - del_kubernetes_master_lb

- name: "删除 res 临时目录"
  gather_facts: no
  hosts: all
  roles:
  - del_res_tmp
  tags:
  - del_res_tmp

- name: "删除 cfssl 相关工具"
  gather_facts: no
  hosts: all
  roles:
  - del_cfssl
  tags:
  - del_cfssl

- name: "删除证书"
  gather_facts: no
  hosts: all
  roles:
  - del_cert
  tags:
  - del_cert