- name: 检测etcd服务文件是否存在
  stat:
    path: /etc/systemd/system/etcd.service
  register: file

- name: 停止etcd服务
  become: true
  systemd:
    state: stopped
    enabled: no
    name: etcd
  when: file.stat.exists == true

- name: 删除etcd服务文件
  become: true
  file:
    path: /etc/systemd/system/etcd.service
    state: absent

- name: 删除etcd执行文件
  become: true
  file:
    path: "{{bin_dir}}/{{item}}"
    state: absent
  with_items:
  - "{{bin_files.etcd}}"

- name: 删除etcd数据相关目录
  become: true
  file:
    path: "{{data_base_dir}}/etcd"
    state: absent